# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # global provisioning
  config.vm.provision "file", run: "always", source: ENV["BIN_DIR"] + "/worker", destination: "/vagrant/ansible/files/worker"
  config.vm.provision "ansible_local", run: "always" do |ansible|
    ansible.provisioning_path = "/vagrant/ansible"
    ansible.playbook = "startup.yml"
  end

  # worker_1
  config.vm.define "worker_1" do |worker_1|
    worker_1.vm.box = "ubuntu/trusty64"
    worker_1.vm.hostname = "worker-1"

    #network
    worker_1.vm.network "private_network", ip: "192.168.22.10"

    # vm specs
    worker_1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  # worker_2
  config.vm.define "worker_2" do |worker_2|
    worker_2.vm.box = "ubuntu/trusty64"
    worker_2.vm.hostname = "worker-2"

    #network
    worker_2.vm.network "private_network", ip: "192.168.22.11"

    # vm specs
    worker_2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

end
