# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # global provision
  config.vm.provision "file", run: "always", source: ENV["BIN_DIR"] + "/client", destination: "/vagrant/ansible/files/client"
  config.vm.provision "ansible_local" do |ansible|
    ansible.provisioning_path = "/vagrant/ansible"
    ansible.playbook = "playbook.yml"
  end

  (1..2).each do |i|
    config.vm.define "client_#{i}" do |client|
      client.vm.box = "ubuntu/trusty64"
      client.vm.hostname = "client-#{i}"

      # networking
      client.vm.network "private_network", ip: "192.168.22.2#{i}"

      # vm specs
      client.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end
    end
  end
end
