# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

settings = YAML::load_file ENV["TEST_BED_DIR"] + "/settings.yml"

Vagrant.configure("2") do |config|

  last_point = settings["load_balancer"]["ip_addr"].rindex(".")
  base_ip = settings["load_balancer"]["ip_addr"][0, last_point + 1]

  # load_balancer
  config.vm.define "load_balancer" do |load_balancer|
    load_balancer.vm.box = "ubuntu/trusty64"
    load_balancer.vm.hostname = settings["load_balancer"]["hostname"]

    load_balancer.vm.network "private_network", ip: settings["load_balancer"]["ip_addr"]
    load_balancer.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end

    load_balancer.vm.provision "file", run: "always", source: ENV["BIN_DIR"] + "/" + settings["load_balancer"]["app_name"], destination: "/vagrant/ansible/files/load_balancer"
    load_balancer.vm.provision "ansible_local", run: "always" do |ansible|
      ansible.provisioning_path = "/vagrant/ansible"
      ansible.playbook = settings["load_balancer"]["provision_script"]
    end
  end

  # workers
  (1..settings["workers"]["no_of_workers"]).each do |i|
    base_hostname = settings["workers"]["base_hostname"]
    app_name = settings["workers"]["app_name"]
    app_path = ENV["BIN_DIR"] + "/" + app_name
    provision_script = settings["workers"]["provision_script"]

    if settings.key?("debug") and settings["debug"].key?("lb_address")
      lb_address = settings["debug"]["lb_address"]
    else
      lb_address = settings["load_balancer"]["ip_addr"]
    end

    config.vm.define "worker_#{i}" do |worker|
      worker.vm.box = "ubuntu/trusty64"
      worker.vm.hostname = base_hostname + "-#{i}"

      #network
      worker.vm.network "private_network", ip: base_ip + "#{10 + i}"

      # vm specs
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end

      worker.vm.provision "file", run: "always", source: app_path, destination: "/vagrant/ansible/files/" + app_name
      worker.vm.provision "ansible_local", run: "always" do |ansible|
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.playbook = provision_script
        ansible.extra_vars = {
          lb_address: lb_address
        }
      end
    end
  end

  # clients
  (1..settings["clients"]["no_of_clients"]).each do |i|
    base_hostname = settings["clients"]["base_hostname"]
    app_name = settings["clients"]["app_name"]
    app_path = ENV["BIN_DIR"] + "/" + app_name
    provision_script = settings["clients"]["provision_script"]

    if settings.key?("debug") and settings["debug"].key?("lb_address")
      lb_address = settings["debug"]["lb_address"]
    else
      lb_address = settings["load_balancer"]["ip_addr"]
    end

    config.vm.define "client_#{i}" do |client|
      client.vm.box = "ubuntu/trusty64"
      client.vm.hostname = base_hostname + "-#{i}"

      # network
      client.vm.network "private_network", ip: base_ip + "#{100 + i}"

      # vm specs
      client.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 2
      end

      client.vm.provision "file", run: "always", source: app_path, destination: "/vagrant/ansible/files/" + app_name
      client.vm.provision "ansible_local", run: "always" do |ansible|
        ansible.provisioning_path = "/vagrant/ansible"
        ansible.playbook = provision_script
        ansible.extra_vars = {
          lb_address: lb_address,
          output_listen_port: settings["clients"]["output_listen_port"]
        }
      end
    end
  end
end
