---
- hosts: all
  become: yes

  tasks:
  - name: Save lb_address
    copy: 
      content: "{{ lb_address }}" 
      dest: /vagrant/lb_address

  - name: Save output_listen_port
    copy:
      content: "{{ output_listen_port }}"
      dest: /vagrant/output_listen_port

  - name: Copy client
    copy:
      src: files/client
      dest: /usr/bin/client
      mode: 755
      force: yes