---
- hosts: load_balancer
  become: yes

  tasks:
  - name: Copy loadBalancer
    copy:
      src: files/load_balancer
      dest: /usr/bin/load_balancer
      mode: 755

  - name: Stop load_balancer
    shell: kill $(pidof load_balancer)
    ignore_errors: yes

  - name: Start load_balancer
    shell: /usr/bin/load_balancer &
