---
- hosts: all
  become: yes

  tasks:
  - name: Copy worker
    copy:
      src: files/worker
      dest: /usr/bin/worker_lb
      mode: 755
       
  - name: Start worker
    shell: /usr/bin/worker_lb &
    environment:
      LOAD_BALANCER_ADDRESS: "{{ lb_address }}"
