load_balancer:
  ip_addr: "192.168.111.2"
  hostname: "load-balancer"

workers:
  no_of_workers: 3
  base_hostname: "worker"

clients:
  no_of_clients: 15
  base_hostname: "client"
  output_listen_port: 7893

clients_fast:
  no_of_clients: 5
  base_hostname: "client-fast"
  output_listen_port: 7893

# debug:
#   lb_address: "192.168.111.1"
