---
- hosts: default
  become: yes
  vars:
    lb_address: 192.168.22.2

  tasks:
  - name: Copy worker
    copy:
      src: files/worker
      dest: /usr/bin/worker_lb
      mode: 755

  - name: Start worker
    shell: /usr/bin/worker_lb &
    environment:
      LOAD_BALANCER_ADDRESS: "{{ lb_address }}"
